version: "3.9"

services: 
  mysql:
    image: mysql:8.0
    container_name: mysql_devsu
    restart: always
    environment: 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: clientes
    ports: 
      - "3306:3306"
    volumes: 
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5     
    networks:
      - cliente-net 

  cliente-api:
    build:
      context: .
      dockerfile: DockerFile
    container_name: clientes-api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clientes
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - cliente-net


volumes:
  mysql_data:

networks:
  cliente-net:
    driver: bridge